# -*- coding: utf-8 -*-
"""automate_Ade Suryadi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QC_9mH9fBod8Ywc1QfEglQeqYxy8-Yz7
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
import os

def run_preprocessing():
    print("Memulai proses automasi preprocessing...")

    # 1. Membaca data mentah dari folder sebelah
    # Script ini ada di folder 'preprocessing', jadi kita mundur satu langkah '../'
    df = pd.read_csv('../dataset_raw/heart.csv')

    # 2. Membersihkan data duplikat
    df_clean = df.drop_duplicates()

    # 3. Encoding (Mengubah teks menjadi angka)
    kolom_kategorikal = df_clean.select_dtypes(include=['object']).columns
    df_encoded = pd.get_dummies(df_clean, columns=kolom_kategorikal, drop_first=True)

    # 4. Scaling (Menyamakan skala angka)
    kolom_numerik = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
    scaler = StandardScaler()
    df_encoded[kolom_numerik] = scaler.fit_transform(df_encoded[kolom_numerik])

    # 5. Menyimpan data yang sudah bersih
    # Kita simpan di folder preprocessing ini juga sesuai kriteria Dicoding
    output_filename = 'heart_preprocessing.csv'
    df_encoded.to_csv(output_filename, index=False)

    print(f"Selesai! Data bersih berhasil disimpan sebagai: {output_filename}")

if __name__ == "__main__":
    run_preprocessing()
